import type { Metadata } from "next";
import { FontProvider, getFontClassName } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: {
    apple: "/globe.svg",
  },
};

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FooterWrapper from "@/components/FooterWrapper";
import WelcomePopup from "@/components/WelcomePopup";
import PushNotificationManager from "@/components/PushNotificationManager";
import { prisma } from "@/lib/prisma";
import { getThemeVariables } from "@/lib/themes";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await prisma.settings.findFirst();
  const themeVars = getThemeVariables(settings?.themeColor);

  return (
    <html lang="id" style={themeVars as React.CSSProperties}>
      <body 
        className={`${getFontClassName(settings?.fontFamily)} font-sans antialiased min-h-screen flex flex-col`}
      >
        <FontProvider />
        <WelcomePopup 
          imageUrl={settings?.popupImage || null} 
          isActive={settings?.popupIsActive || false} 
          duration={settings?.popupDuration || 10} 
        />
        <PushNotificationManager />
        <Navbar logoUrl={settings?.logoUrl} logoSize={settings?.logoSizeNavbar} />
        <main className="flex-grow">
          {children}
        </main>
        <FooterWrapper>
          <Footer />
        </FooterWrapper>
      </body>
    </html>
  );
}
